#!/usr/bin/env bash

set -xe

#build binary
GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -o ./bin/buyFallenCoinAt859 ./aws-lambda/buyFallenCoinAt859.go

#create zip
mkdir -p ./pkg
mkdir -p ./tmp

cp .env tmp/.env

pushd bin
zip -FSr ../pkg/buyFallenCoinAt859.zip ./buyFallenCoinAt859
popd

# -j 옵션은 디렉토리 경로를 제외하고 파일만 압축하도록 명령
zip -j ./pkg/buyFallenCoinAt859.zip tmp/.env

AWS_PROFILE=myungsworld aws lambda update-function-code --function-name "buyFallenCoinAt859" --zip-file fileb://pkg/buyFallenCoinAt859.zip --region ap-northeast-2